dist: bionic
services:
  - xvfb
language: ruby
rvm:
  - 2.7
install:
  - sudo apt-get install -y libgtk-3-dev
  - bundle install
script: bundle exec rake spec
notifications:
  email:
    on_success: never
    on_failure: change
